MACOSX_DEPLOYMENT_TARGET:  # [osx and not arm64]
  - '10.13'                # [osx and not arm64]
c_compiler:                # [win]
- vs2019                   # [win]
cxx_compiler:              # [win]
- vs2019                   # [win]
