{% set name = "correctionlib" %}
{% set version = "2.6.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/correctionlib-{{ version }}.tar.gz
  sha256: 3268511c9061889647d08d5c6fdf099ce368edc13473faabb21cd2e523025dfd
  patches: setup.patch

build:
  number: 0
  entry_points:
    - correction = correctionlib.cli:main
  script:
    # Travis ppc64le doesn't have enough memory to build in more than one thread.
    - export CMAKE_BUILD_PARALLEL_LEVEL=${CPU_COUNT}  # [not (linux and ppc64le)]
    - export CMAKE_BUILD_PARALLEL_LEVEL=1             # [linux and ppc64le]
    - {{ PYTHON }} -m pip install . -vv


requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - cmake
    - make  # [unix]
  host:
    - pip
    - python
    - setuptools-scm
    - scikit-build
    - zlib
  run:
    - packaging
    - numpy >=1.13.3
    - pydantic >=2
    - python
    - rich
    - typing-extensions  # [py<38]

test:
  imports:
    - correctionlib
  commands:
    - pip check
    - correction --help
  requires:
    - pip

about:
  home: https://github.com/cms-nanoAOD/correctionlib
  summary: A generic correction library
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - lgray
    - nsmith-
    - pieterdavid
    - IzaakWN
